// Native installer bookkeeping. No Python/PowerShell runtime is required.
// Wire format is generated by scripts/build_installer_inventory.py.

const
  OwnedManifestHeader = 'FPVS-TOOLBOX-OWNED-FILES-1';
  OwnedCurrentName = 'fpvs-owned-files-v1.txt';
  OwnedPendingName = 'fpvs-pending-owned-files-v1.txt';
  OwnedMaxManifestBytes = 67108864;
  OwnedMaxRecords = 250000;
  OwnedInvalidAttributes = $FFFFFFFF;
  OwnedInvalidHandle = -1;
  OwnedDirectoryAttribute = $10;
  OwnedReparseAttribute = $400;
  OwnedReadAccess = $80000000;
  OwnedWriteAccess = $40000000;
  OwnedDeleteAccess = $10000;
  OwnedReadAttributes = $80;
  OwnedShareRead = 1;
  OwnedShareWrite = 2;
  OwnedOpenExisting = 3;
  OwnedCreateNew = 1;
  OwnedOpenAlways = 4;
  OwnedOpenReparsePoint = $200000;
  OwnedBackupSemantics = $2000000;
  OwnedCSIDLProfile = $0028;

type
  TOwnedHandles = array of THandle;
  TOwnedFileInfo = record
    Attributes: Cardinal;
    CreationLow: Cardinal;
    CreationHigh: Cardinal;
    AccessLow: Cardinal;
    AccessHigh: Cardinal;
    WriteLow: Cardinal;
    WriteHigh: Cardinal;
    VolumeSerial: Cardinal;
    SizeHigh: Cardinal;
    SizeLow: Cardinal;
    LinkCount: Cardinal;
    IndexHigh: Cardinal;
    IndexLow: Cardinal;
  end;

function OwnedCreateFile(Name: String; Access, Share: Cardinal; Security: THandle;
  Creation, Flags: Cardinal; Template: THandle): THandle;
  external 'CreateFileW@kernel32.dll stdcall';
function OwnedGetFileInfo(Handle: THandle; var Info: TOwnedFileInfo): Boolean;
  external 'GetFileInformationByHandle@kernel32.dll stdcall';
function OwnedCloseHandle(Handle: THandle): Boolean;
  external 'CloseHandle@kernel32.dll stdcall';
function OwnedGetAttributes(Name: String): Cardinal;
  external 'GetFileAttributesW@kernel32.dll stdcall';
function OwnedLastError: Cardinal;
  external 'GetLastError@kernel32.dll stdcall';
function OwnedSetDisposition(Handle: THandle; InfoClass: Integer;
  var DeleteFlag: Byte; Size: Cardinal): Boolean;
  external 'SetFileInformationByHandle@kernel32.dll stdcall';
function OwnedFlushFile(Handle: THandle): Boolean;
  external 'FlushFileBuffers@kernel32.dll stdcall';
function OwnedMoveFile(OldName, NewName: String; Flags: Cardinal): Boolean;
  external 'MoveFileExW@kernel32.dll stdcall';

var
  OwnedCurrentRecords: TStringList;
  OwnedCurrentPaths: TStringList;
  OwnedPreviousRecords: TStringList;
  OwnedPreparedRoot: String;
  OwnedPriorManifestHash: String;
  OwnedRootGuards: TOwnedHandles;

function OwnedNewList: TStringList;
begin
  Result := TStringList.Create;
  Result.CaseSensitive := False;
  Result.Duplicates := dupIgnore;
  Result.Sorted := True;
end;

procedure OwnedReleaseGuards(var Handles: TOwnedHandles);
var
  I: Integer;
begin
  for I := GetArrayLength(Handles) - 1 downto 0 do
    OwnedCloseHandle(Handles[I]);
  SetArrayLength(Handles, 0);
end;

function OwnedPinDirectory(const Path: String; var Handles: TOwnedHandles;
  var Missing: Boolean): Boolean;
var
  Handle: THandle;
  Info: TOwnedFileInfo;
  Count: Integer;
  ErrorCode: Cardinal;
begin
  Result := False;
  Missing := False;
  Handle := OwnedCreateFile(Path, OwnedReadAttributes, OwnedShareRead or OwnedShareWrite,
    0, OwnedOpenExisting, OwnedOpenReparsePoint or OwnedBackupSemantics, 0);
  if Handle = OwnedInvalidHandle then begin
    ErrorCode := OwnedLastError;
    Missing := (ErrorCode = 2) or (ErrorCode = 3);
    Exit;
  end;
  if (not OwnedGetFileInfo(Handle, Info)) or
    ((Info.Attributes and OwnedDirectoryAttribute) = 0) or
    ((Info.Attributes and OwnedReparseAttribute) <> 0) then begin
    OwnedCloseHandle(Handle);
    Exit;
  end;
  Count := GetArrayLength(Handles);
  SetArrayLength(Handles, Count + 1);
  Handles[Count] := Handle;
  Result := True;
end;

function OwnedLocalAbsolutePath(const Path: String): Boolean;
var
  I: Integer;
begin
  Result := False;
  if Length(Path) <= 3 then
    Exit;
  if (Pos(Uppercase(Path[1]), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') = 0) or
    (Path[2] <> ':') or (Path[3] <> '\') then
    Exit;
  for I := 4 to Length(Path) do
    if (Ord(Path[I]) < 32) or (Pos(Path[I], '/:*?"<>|') > 0) then
      Exit;
  if not SameText(RemoveBackslashUnlessRoot(ExpandFileName(Path)), Path) then
    Exit;
  Result := True;
end;

function OwnedGuardDirectoryChain(const Directory: String; AllowMissing: Boolean;
  var Handles: TOwnedHandles; var Missing: Boolean): Boolean;
var
  I, Start: Integer;
  Prefix, Part: String;
begin
  Result := False;
  Missing := False;
  SetArrayLength(Handles, 0);
  if not OwnedLocalAbsolutePath(Directory) then
    Exit;
  Prefix := Copy(Directory, 1, 3);
  if not OwnedPinDirectory(Prefix, Handles, Missing) then
    Exit;
  Start := 4;
  for I := 4 to Length(Directory) + 1 do begin
    if (I > Length(Directory)) or (Directory[I] = '\') then begin
      Part := Copy(Directory, Start, I - Start);
      if (Part = '') or (Part = '.') or (Part = '..') or
        (Part[Length(Part)] = '.') or (Part[Length(Part)] = ' ') then begin
        OwnedReleaseGuards(Handles);
        Exit;
      end;
      Prefix := AddBackslash(Prefix) + Part;
      if not OwnedPinDirectory(Prefix, Handles, Missing) then begin
        if AllowMissing and Missing then begin
          Result := True;
          Exit;
        end;
        OwnedReleaseGuards(Handles);
        Exit;
      end;
      Start := I + 1;
    end;
  end;
  Result := True;
end;

function OwnedGuardDirectories(const Directory: String; AllowMissing: Boolean;
  var Handles: TOwnedHandles): Boolean;
var
  Missing: Boolean;
begin
  Result := OwnedGuardDirectoryChain(Directory, AllowMissing, Handles, Missing);
end;

function OwnedSafeInstallRoot(const Root: String): Boolean;
var
  Blocked: TArrayOfString;
  I: Integer;
  Parent: String;
begin
  Result := False;
  if not OwnedLocalAbsolutePath(Root) then
    Exit;
  SetArrayLength(Blocked, 12);
  // Resolve the profile through Windows without creating a directory or trusting env vars.
  Blocked[0] := RemoveBackslashUnlessRoot(
    GetShellFolderByCSIDL(OwnedCSIDLProfile, False));
  if not OwnedLocalAbsolutePath(Blocked[0]) then
    Exit;
  Blocked[1] := ExpandConstant('{localappdata}');
  Blocked[2] := ExpandConstant('{userappdata}');
  Blocked[3] := ExpandConstant('{userdocs}');
  Blocked[4] := ExpandConstant('{userdesktop}');
  Blocked[5] := ExpandConstant('{commonappdata}');
  Blocked[6] := ExpandConstant('{commonpf}');
  Blocked[7] := ExpandConstant('{commoncf}');
  Blocked[8] := ExpandConstant('{win}');
  Blocked[9] := ExpandConstant('{sys}');
  Blocked[10] := ExpandConstant('{tmp}');
  Blocked[11] := ExpandConstant('{localappdata}\FPVS Toolbox\updates');
  for I := 0 to GetArrayLength(Blocked) - 1 do
    if SameText(Root, RemoveBackslashUnlessRoot(Blocked[I])) then
      Exit;
  if Pos(Lowercase(AddBackslash(ExpandConstant('{win}'))), Lowercase(Root)) = 1 then
    Exit;
  if Pos(Lowercase(AddBackslash(Blocked[11])), Lowercase(Root)) = 1 then
    Exit;
  Parent := Root;
  while Length(Parent) > 3 do begin
    if FileExists(AddBackslash(Parent) + 'project.json') or
      DirExists(AddBackslash(Parent) + '.fpvs-toolbox') or
      SameText(ExtractFileName(Parent), '.fpvs-toolbox') then
      Exit;
    Parent := ExtractFileDir(Parent);
  end;
  Result := True;
end;

function OwnedSafeRelativePath(const Path: String): Boolean;
var
  I, Start, Dot: Integer;
  Part, Device, Top: String;
begin
  Result := False;
  if (Length(Path) = 0) or (Length(Path) > 1024) then
    Exit;
  Start := 1;
  Top := '';
  for I := 1 to Length(Path) + 1 do begin
    if I <= Length(Path) then
      if (Ord(Path[I]) < 32) or (Ord(Path[I]) = 127) or
        (Pos(Path[I], '<>:"\|?*') > 0) then
        Exit;
    if (I > Length(Path)) or (Path[I] = '/') then begin
      Part := Copy(Path, Start, I - Start);
      if (Part = '') or (Part = '.') or (Part = '..') then
        Exit;
      if (Part[Length(Part)] = '.') or (Part[Length(Part)] = ' ') then
        Exit;
      Device := Lowercase(Part);
      Dot := Pos('.', Device);
      if Dot > 0 then
        Device := Copy(Device, 1, Dot - 1);
      if (Device = 'con') or (Device = 'prn') or (Device = 'aux') or
        (Device = 'nul') or (Device = 'clock$') then
        Exit;
      if (Length(Device) = 4) and
        ((Copy(Device, 1, 3) = 'com') or (Copy(Device, 1, 3) = 'lpt')) and
        (Pos(Device[4], '123456789¹²³') > 0) then
        Exit;
      if Top = '' then
        Top := Lowercase(Part);
      Start := I + 1;
    end;
  end;
  if (Top = '.fpvs-toolbox') or (Top = 'cache') or (Top = 'logs') or
    (Top = 'project.json') or (Top = 'runs') or (Top = 'stimuli') or
    (Top = OwnedCurrentName) or (Top = OwnedPendingName) or
    (Top = 'fpvs-patch-transaction-v1.txt') then
    Exit;
  if (Pos('/', Path) = 0) and (Copy(Top, 1, 5) = 'unins') then
    Exit;
  Result := True;
end;

function OwnedValidHash(const Hash: String): Boolean;
var
  I: Integer;
begin
  Result := False;
  if Length(Hash) <> 64 then
    Exit;
  for I := 1 to Length(Hash) do
    if Pos(Hash[I], '0123456789abcdef') = 0 then
      Exit;
  Result := True;
end;

function OwnedVersionDigits(const Value: String; var Position: Integer): Boolean;
var
  Start: Integer;
begin
  Start := Position;
  while Position <= Length(Value) do begin
    if Pos(Value[Position], '0123456789') = 0 then
      Break;
    Position := Position + 1;
  end;
  Result := Position > Start;
end;

function OwnedVersionLabel(const Value, Labels: String; var Position: Integer): Boolean;
var
  Candidate, Start, I: Integer;
  LabelText: String;
begin
  Result := False;
  Candidate := Position;
  if Candidate <= Length(Value) then
    if Pos(Value[Candidate], '.-_') > 0 then
      Candidate := Candidate + 1;
  Start := 1;
  for I := 1 to Length(Labels) + 1 do begin
    if (I > Length(Labels)) or (Labels[I] = '|') then begin
      LabelText := Copy(Labels, Start, I - Start);
      if Copy(Value, Candidate, Length(LabelText)) = LabelText then begin
        Position := Candidate + Length(LabelText);
        if Position <= Length(Value) then
          if Pos(Value[Position], '.-_') > 0 then
            Position := Position + 1;
        OwnedVersionDigits(Value, Position);
        Result := True;
        Exit;
      end;
      Start := I + 1;
    end;
  end;
end;

function OwnedValidVersion(const Version: String): Boolean;
var
  Value: String;
  Position, Saved, Start: Integer;
begin
  // PEP 440's digit-start form used by updater filenames (no epoch or leading v).
  Result := False;
  Value := Lowercase(Version);
  Position := 1;
  if not OwnedVersionDigits(Value, Position) then
    Exit;
  while Position < Length(Value) do begin
    if (Value[Position] <> '.') or (Pos(Value[Position + 1], '0123456789') = 0) then
      Break;
    Position := Position + 1;
    OwnedVersionDigits(Value, Position);
  end;
  OwnedVersionLabel(Value, 'preview|alpha|beta|pre|rc|a|b|c', Position);
  Saved := Position;
  if Position <= Length(Value) then begin
    if Value[Position] = '-' then begin
      Position := Position + 1;
      if not OwnedVersionDigits(Value, Position) then
        Position := Saved;
    end;
  end;
  if Position = Saved then
    OwnedVersionLabel(Value, 'post|rev|r', Position);
  OwnedVersionLabel(Value, 'dev', Position);
  if Position <= Length(Value) then begin
    if Value[Position] <> '+' then
      Exit;
    Position := Position + 1;
    Start := Position;
    while Position <= Length(Value) do begin
      if Pos(Value[Position], 'abcdefghijklmnopqrstuvwxyz0123456789') > 0 then
        Position := Position + 1
      else if Pos(Value[Position], '.-_') > 0 then begin
        if Position = Start then
          Exit;
        Position := Position + 1;
        Start := Position;
      end
      else
        Exit;
    end;
    if Position = Start then
      Exit;
  end;
  Result := Position > Length(Value);
end;

function OwnedRecordPath(const RecordText: String): String;
begin
  Result := Copy(RecordText, 1, Pos('|', RecordText) - 1);
end;

function OwnedTarget(const Root, Relative: String): String;
var
  NativeRelative: String;
begin
  NativeRelative := Relative;
  StringChangeEx(NativeRelative, '/', '\', True);
  Result := AddBackslash(Root) + NativeRelative;
end;

function OwnedOpenRegular(const FullPath: String; ForDeletion: Boolean;
  var Handle: THandle; var Guards: TOwnedHandles; var Missing: Boolean): Boolean;
var
  Access, ErrorCode: Cardinal;
  Info: TOwnedFileInfo;
begin
  Result := False;
  Missing := False;
  Handle := OwnedInvalidHandle;
  if not OwnedGuardDirectoryChain(ExtractFileDir(FullPath), False, Guards, Missing) then begin
    Exit;
  end;
  Access := OwnedReadAccess;
  if ForDeletion then
    Access := Access or OwnedDeleteAccess;
  Handle := OwnedCreateFile(FullPath, Access, OwnedShareRead, 0,
    OwnedOpenExisting, OwnedOpenReparsePoint, 0);
  if Handle = OwnedInvalidHandle then begin
    ErrorCode := OwnedLastError;
    Missing := (ErrorCode = 2) or (ErrorCode = 3);
    OwnedReleaseGuards(Guards);
    Exit;
  end;
  if (not OwnedGetFileInfo(Handle, Info)) or
    ((Info.Attributes and (OwnedDirectoryAttribute or OwnedReparseAttribute)) <> 0) or
    (Info.LinkCount <> 1) then begin
    OwnedCloseHandle(Handle);
    Handle := OwnedInvalidHandle;
    OwnedReleaseGuards(Guards);
    Exit;
  end;
  Result := True;
end;

function OwnedReadManifest(const FullPath, ExpectedKind: String;
  Records: TStringList): Boolean;
var
  Lines: TArrayOfString;
  I, Separator: Integer;
  Info: TOwnedFileInfo;
  Handle: THandle;
  Guards: TOwnedHandles;
  Missing: Boolean;
  Path, Hash: String;
  HasExecutable: Boolean;
begin
  Result := False;
  Records.Clear;
  if not OwnedOpenRegular(FullPath, False, Handle, Guards, Missing) then
    Exit;
  try
    if (not OwnedGetFileInfo(Handle, Info)) or (Info.SizeHigh <> 0) or
      (Info.SizeLow > OwnedMaxManifestBytes) then
      Exit;
    if not LoadStringsFromFile(FullPath, Lines) then
      Exit;
    if (GetArrayLength(Lines) < 3) or
      (GetArrayLength(Lines) > OwnedMaxRecords + 3) then
      Exit;
    if (Lines[0] <> OwnedManifestHeader) or (Lines[1] <> 'kind=' + ExpectedKind) then
      Exit;
    if ExpectedKind = 'current' then begin
      if (Copy(Lines[2], 1, 8) <> 'version=') or
        (not OwnedValidVersion(Copy(Lines[2], 9, Length(Lines[2])))) then
        Exit;
    end
    else if Lines[2] <> 'version=' + ExpectedKind then
      Exit;
    HasExecutable := False;
    for I := 3 to GetArrayLength(Lines) - 1 do begin
      Separator := Pos('|', Lines[I]);
      if Separator <= 1 then
        Exit;
      Path := Copy(Lines[I], 1, Separator - 1);
      Hash := Copy(Lines[I], Separator + 1, Length(Lines[I]));
      if (not OwnedSafeRelativePath(Path)) or (not OwnedValidHash(Hash)) or
        (Records.IndexOf(Lines[I]) >= 0) then
        Exit;
      Records.Add(Lines[I]);
      if SameText(Path, '{#AppExeName}') then
        HasExecutable := True;
    end;
    if ((ExpectedKind = 'current') or ((ExpectedKind = 'legacy') and (Records.Count > 0))) and (not HasExecutable) then
      Exit;
    Result := True;
  finally
    OwnedCloseHandle(Handle);
    OwnedReleaseGuards(Guards);
    if not Result then
      Records.Clear;
  end;
end;

function OwnedHashFile(const FullPath: String; var Hash: String): Boolean;
var
  Handle: THandle;
  Guards: TOwnedHandles;
  Missing: Boolean;
  Stream: THandleStream;
begin
  Result := False;
  Hash := '';
  if not OwnedOpenRegular(FullPath, False, Handle, Guards, Missing) then
    Exit;
  try
    Stream := THandleStream.Create(Handle);
    try
      Hash := Lowercase(GetSHA256OfStream(Stream));
      Result := OwnedValidHash(Hash);
    finally
      Stream.Free;
    end;
  finally
    OwnedCloseHandle(Handle);
    OwnedReleaseGuards(Guards);
  end;
end;

function OwnedWritePending(const Root: String; Records: TStringList): Boolean;
var
  Guards: TOwnedHandles;
  Temporary, Destination: String;
  Lines: TStringList;
  Data: AnsiString;
  Handle: THandle;
  Stream: THandleStream;
  I: Integer;
  CreatedTemporary: Boolean;
begin
  Result := False;
  if Records.Count > OwnedMaxRecords then begin
    Log('Ownership: combined pending history exceeds the record limit; preserving the existing journal.');
    Exit;
  end;
  if not OwnedGuardDirectories(Root, False, Guards) then
    Exit;
  Temporary := '';
  CreatedTemporary := False;
  try
    Destination := OwnedTarget(Root, OwnedPendingName);
    if (OwnedGetAttributes(Destination) <> OwnedInvalidAttributes) and
      ((OwnedGetAttributes(Destination) and (OwnedReparseAttribute or OwnedDirectoryAttribute)) <> 0) then
      Exit;
    Lines := TStringList.Create;
    try
      Lines.Add(OwnedManifestHeader);
      Lines.Add('kind=pending');
      Lines.Add('version=pending');
      for I := 0 to Records.Count - 1 do
        Lines.Add(Records[I]);
      Data := Utf8Encode(#$FEFF + Lines.Text);
    finally
      Lines.Free;
    end;
    if Length(Data) > OwnedMaxManifestBytes then begin
      Log('Ownership: combined pending history exceeds the byte limit; preserving the existing journal.');
      Exit;
    end;
    Temporary := GenerateUniqueName(Root, '.fpvs-owned-pending.tmp');
    Handle := OwnedCreateFile(Temporary, OwnedWriteAccess, 0, 0, OwnedCreateNew, $80, 0);
    if Handle = OwnedInvalidHandle then
      Exit;
    CreatedTemporary := True;
    try
      Stream := THandleStream.Create(Handle);
      try
        Stream.WriteBuffer(Data, Length(Data));
        if not OwnedFlushFile(Handle) then
          Exit;
      finally
        Stream.Free;
      end;
    finally
      OwnedCloseHandle(Handle);
    end;
    // MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH, same-volume atomic replacement.
    Result := OwnedMoveFile(Temporary, Destination, 9);
    if Result then
      CreatedTemporary := False;
  finally
    if CreatedTemporary then
      DeleteFile(Temporary);
    OwnedReleaseGuards(Guards);
  end;
end;

procedure OwnedBuildCurrentIndexes;
var
  I: Integer;
  Path: String;
begin
  for I := 0 to OwnedCurrentRecords.Count - 1 do begin
    Path := OwnedRecordPath(OwnedCurrentRecords[I]);
    OwnedCurrentPaths.Add(Path);
  end;
end;

procedure OwnedAddObsolete(Source: TStringList);
var
  I: Integer;
begin
  for I := 0 to Source.Count - 1 do
    if OwnedCurrentPaths.IndexOf(OwnedRecordPath(Source[I])) < 0 then
      OwnedPreviousRecords.Add(Source[I]);
end;

function OwnedDestinationsSafe(const Root: String): Boolean;
var
  I: Integer;
  FullPath: String;
  Attributes: Cardinal;
  Guards: TOwnedHandles;
  FileGuards: TOwnedHandles;
  Handle: THandle;
  Missing: Boolean;
begin
  Result := False;
  for I := 0 to OwnedCurrentPaths.Count - 1 do begin
    FullPath := OwnedTarget(Root, OwnedCurrentPaths[I]);
    if not OwnedGuardDirectories(ExtractFileDir(FullPath), True, Guards) then
      Exit;
    try
      Attributes := OwnedGetAttributes(FullPath);
      if Attributes <> OwnedInvalidAttributes then begin
        if (Attributes and (OwnedDirectoryAttribute or OwnedReparseAttribute)) <> 0 then
          Exit;
        if not OwnedOpenRegular(FullPath, False, Handle, FileGuards, Missing) then
          Exit;
        OwnedCloseHandle(Handle);
        OwnedReleaseGuards(FileGuards);
      end;
    finally
      OwnedReleaseGuards(Guards);
    end;
  end;
  Result := True;
end;

procedure OwnedDisposeState;
begin
  OwnedReleaseGuards(OwnedRootGuards);
  if OwnedCurrentRecords <> nil then
    OwnedCurrentRecords.Free;
  if OwnedCurrentPaths <> nil then
    OwnedCurrentPaths.Free;
  if OwnedPreviousRecords <> nil then
    OwnedPreviousRecords.Free;
  OwnedCurrentRecords := nil;
  OwnedCurrentPaths := nil;
  OwnedPreviousRecords := nil;
  OwnedPreparedRoot := '';
  OwnedPriorManifestHash := '';
end;

function OwnedPrepareUpgrade: String;
var
  Root, Path, Hash: String;
  Previous, Legacy: TStringList;
begin
  Result := '';
  OwnedDisposeState;
  Root := RemoveBackslashUnlessRoot(ExpandConstant('{app}'));
  if (not OwnedSafeInstallRoot(Root)) or
    (not OwnedGuardDirectories(Root, True, OwnedRootGuards)) then begin
    Result := 'Choose a dedicated local application folder without links, junctions, or project data.';
    Exit;
  end;
  OwnedCurrentRecords := OwnedNewList;
  OwnedCurrentPaths := OwnedNewList;
  OwnedPreviousRecords := OwnedNewList;
  Previous := OwnedNewList;
  Legacy := OwnedNewList;
  try
    ExtractTemporaryFile('current-owned-files.txt');
    ExtractTemporaryFile('legacy-owned-files.txt');
    if (not OwnedReadManifest(ExpandConstant('{tmp}\current-owned-files.txt'), 'current', OwnedCurrentRecords)) or
      (not OwnedReadManifest(ExpandConstant('{tmp}\legacy-owned-files.txt'), 'legacy', Legacy)) then begin
      Result := 'The installer ownership inventory is invalid. Download a fresh official installer.';
      Exit;
    end;
    OwnedBuildCurrentIndexes;
    if not OwnedDestinationsSafe(Root) then begin
      Result := 'The installation folder contains a link or unsafe destination. No files were replaced.';
      Exit;
    end;
    Path := OwnedTarget(Root, OwnedCurrentName);
    if OwnedGetAttributes(Path) <> OwnedInvalidAttributes then begin
      if not OwnedReadManifest(Path, 'current', Previous) then begin
        Result := 'The existing application ownership manifest is invalid. No files were replaced.';
        Exit;
      end;
      OwnedHashFile(Path, OwnedPriorManifestHash);
      OwnedAddObsolete(Previous);
    end
    else if OwnedHashFile(OwnedTarget(Root, '{#AppExeName}'), Hash) then begin
      if Legacy.IndexOf('{#AppExeName}|' + Hash) >= 0 then begin
        // Include every published ancestor, not just the version currently displayed.
        OwnedAddObsolete(Legacy);
        Log('Ownership: authenticated published-release ancestry selected.');
      end
      else
        Log('Ownership: unrecognized existing executable; unknown files will be preserved.');
    end;
    Path := OwnedTarget(Root, OwnedPendingName);
    if OwnedGetAttributes(Path) <> OwnedInvalidAttributes then begin
      if not OwnedReadManifest(Path, 'pending', Previous) then begin
        Result := 'The pending application ownership manifest is invalid. No files were replaced.';
        Exit;
      end;
      OwnedAddObsolete(Previous);
    end;
    // Preserve the old ownership durably BEFORE Inno replaces any application files.
    // A failed/canceled install never runs reconciliation; this journal remains retryable.
    if (OwnedPreviousRecords.Count > 0) and (not OwnedWritePending(Root, OwnedPreviousRecords)) then begin
      Result := 'Could not preserve upgrade ownership history. Close other programs and retry.';
      Exit;
    end;
    OwnedPreparedRoot := Root;
    Log(Format('Ownership: captured %d obsolete hash records before replacement.', [OwnedPreviousRecords.Count]));
  finally
    Previous.Free;
    Legacy.Free;
  end;
end;

procedure OwnedRemoveRecoveredPatchMarker;
var
  Handle: THandle;
  Guards: TOwnedHandles;
  Missing: Boolean;
  Info: TOwnedFileInfo;
  Lines: TStringList;
  Stream: THandleStream;
  Data: AnsiString;
  CurrentHash, SourceHash, TargetHash, Marker, MarkerText: String;
  DeleteFlag: Byte;
begin
  if OwnedPreparedRoot = '' then
    Exit;
  Marker := OwnedTarget(OwnedPreparedRoot, 'fpvs-patch-transaction-v1.txt');
  if not OwnedOpenRegular(Marker, True, Handle, Guards, Missing) then
    Exit;
  Lines := TStringList.Create;
  try
    if (not OwnedGetFileInfo(Handle, Info)) or (Info.SizeHigh <> 0) or
      (Info.SizeLow > 2048) then
      Exit;
    // Parse through the deletion handle. Reopening without share-delete would fail.
    SetLength(Data, Info.SizeLow);
    Stream := THandleStream.Create(Handle);
    try
      if Info.SizeLow > 0 then
        Stream.ReadBuffer(Data, Info.SizeLow);
    finally
      Stream.Free;
    end;
    MarkerText := Utf8Decode(Data);
    if (Length(MarkerText) > 0) and (MarkerText[1] = #$FEFF) then
      Delete(MarkerText, 1, 1);
    Lines.Text := MarkerText;
    if Lines.Count <> 5 then
      Exit;
    if (Lines[0] <> 'FPVS-TOOLBOX-PATCH-TRANSACTION-1') or
      (Copy(Lines[1], 1, 5) <> 'from=') or
      (not OwnedValidVersion(Copy(Lines[1], 6, Length(Lines[1])))) or
      (Copy(Lines[2], 1, 3) <> 'to=') or
      (not OwnedValidVersion(Copy(Lines[2], 4, Length(Lines[2])))) or
      (Copy(Lines[3], 1, 7) <> 'source=') or
      (Copy(Lines[4], 1, 7) <> 'target=') then
      Exit;
    SourceHash := Copy(Lines[3], 8, Length(Lines[3]));
    TargetHash := Copy(Lines[4], 8, Length(Lines[4]));
    if (not OwnedValidHash(SourceHash)) or (not OwnedValidHash(TargetHash)) then
      Exit;
    if not OwnedHashFile(OwnedTarget(OwnedPreparedRoot, OwnedCurrentName), CurrentHash) then
      Exit;
    // A full repair may retire only a transaction bound to its prior or target inventory.
    // A similarly named unknown file or unrelated fingerprint remains untouched.
    if (SourceHash <> OwnedPriorManifestHash) and (TargetHash <> OwnedPriorManifestHash) and
      (SourceHash <> CurrentHash) and (TargetHash <> CurrentHash) then
      Exit;
    DeleteFlag := 1;
    if not OwnedSetDisposition(Handle, 4, DeleteFlag, 1) then
      Log('Ownership: completed patch-recovery marker remains for retry.');
  finally
    Lines.Free;
    OwnedCloseHandle(Handle);
    OwnedReleaseGuards(Guards);
  end;
end;

function OwnedDeleteKnownFile(const Root, Relative: String; Records: TStringList): Boolean;
var
  Handle: THandle;
  Guards: TOwnedHandles;
  Missing: Boolean;
  Stream: THandleStream;
  Hash: String;
  DeleteFlag: Byte;
begin
  Result := False;
  if not OwnedSafeRelativePath(Relative) then
    Exit;
  if not OwnedOpenRegular(OwnedTarget(Root, Relative), True, Handle, Guards, Missing) then begin
    Result := Missing;
    if not Missing then
      Log('Ownership: retaining inaccessible/linked obsolete file: ' + Relative);
    Exit;
  end;
  try
    Stream := THandleStream.Create(Handle);
    try
      Hash := Lowercase(GetSHA256OfStream(Stream));
    finally
      Stream.Free;
    end;
    if Records.IndexOf(Relative + '|' + Hash) < 0 then begin
      Log('Ownership: preserving modified or unrecognized file: ' + Relative);
      Exit;
    end;
    // Hash and delete the SAME open, single-link file while ancestors cannot be renamed.
    DeleteFlag := 1;
    Result := OwnedSetDisposition(Handle, 4, DeleteFlag, 1);
    if Result then
      Log('Ownership: removed obsolete packaged file: ' + Relative)
    else
      Log('Ownership: retaining locked/read-only obsolete file for retry: ' + Relative);
  finally
    OwnedCloseHandle(Handle);
    OwnedReleaseGuards(Guards);
  end;
end;

procedure OwnedKeepPathRecords(const Path: String; Source, Destination: TStringList);
var
  Index: Integer;
begin
  Source.Find(Path + '|', Index);
  while Index < Source.Count do begin
    if not SameText(OwnedRecordPath(Source[Index]), Path) then
      Break;
    Destination.Add(Source[Index]);
    Index := Index + 1;
  end;
end;

procedure OwnedReconcileAfterSuccess;
var
  Paths, Remaining: TStringList;
  I: Integer;
  Path, Hash: String;
begin
  if (OwnedPreparedRoot = '') or (OwnedPreviousRecords = nil) then
    Exit;
  if not OwnedSafeInstallRoot(OwnedPreparedRoot) then begin
    Log('Ownership: cleanup skipped because the installation root is unsafe.');
    Exit;
  end;
  if (not OwnedHashFile(OwnedTarget(OwnedPreparedRoot, '{#AppExeName}'), Hash)) or
    (OwnedCurrentRecords.IndexOf('{#AppExeName}|' + Hash) < 0) then begin
    Log('Ownership: new executable identity could not be verified; cleanup remains pending.');
    Exit;
  end;
  Paths := OwnedNewList;
  Remaining := OwnedNewList;
  try
    for I := 0 to OwnedPreviousRecords.Count - 1 do
      Paths.Add(OwnedRecordPath(OwnedPreviousRecords[I]));
    for I := 0 to Paths.Count - 1 do begin
      Path := Paths[I];
      try
        if not OwnedDeleteKnownFile(OwnedPreparedRoot, Path, OwnedPreviousRecords) then
          OwnedKeepPathRecords(Path, OwnedPreviousRecords, Remaining);
      except
        Log('Ownership: cleanup error retained for retry: ' + Path + ': ' + GetExceptionMessage);
        OwnedKeepPathRecords(Path, OwnedPreviousRecords, Remaining);
      end;
    end;
    // If this atomic commit fails, the original superset journal still preserves history.
    if not OwnedWritePending(OwnedPreparedRoot, Remaining) then
      Log('Ownership: could not commit cleanup journal; the previous journal is retained.');
  finally
    Remaining.Free;
    Paths.Free;
  end;
end;

procedure OwnedRemovePendingOnUninstall;
var
  Root, Path: String;
  Records: TStringList;
  Handle: THandle;
  Guards: TOwnedHandles;
  Missing: Boolean;
  DeleteFlag: Byte;
begin
  Root := RemoveBackslashUnlessRoot(ExpandConstant('{app}'));
  if not OwnedSafeInstallRoot(Root) then
    Exit;
  Path := OwnedTarget(Root, OwnedPendingName);
  Records := OwnedNewList;
  try
    if not OwnedReadManifest(Path, 'pending', Records) then
      Exit;
    if not OwnedOpenRegular(Path, True, Handle, Guards, Missing) then
      Exit;
    try
      DeleteFlag := 1;
      if not OwnedSetDisposition(Handle, 4, DeleteFlag, 1) then
        Log('Ownership: pending bookkeeping could not be removed during uninstall.');
    finally
      OwnedCloseHandle(Handle);
      OwnedReleaseGuards(Guards);
    end;
  finally
    Records.Free;
  end;
  // Inno may already have tried to remove the directory while our journal existed.
  // This only succeeds if it is empty; unrelated user files are never traversed.
  RemoveDir(Root);
end;
