"""User-facing LORETA method information text."""

from __future__ import annotations

from Main_App.gui.components import SurfaceSize, ToolInfoContent

LORETA_METHOD_INFO_HTML = """
<h2>What This Tool Is Showing</h2>
<p>
The LORETA Visualizer displays an estimate of where an FPVS oddball response
could have arisen on the cortical surface. Source estimation cannot uniquely
recover the true generators of scalp EEG, so these maps should be interpreted
as model-based visual aids rather than anatomical ground truth.
</p>
<p>
The normal FPVS Toolbox workflow is an EEG-only, Hauk-informed L2 minimum-norm
source-PSD analysis. It adapts the sequence used in published FPVS source work
(Hauk et al., 2021) to the Toolbox's user-friendly, fsaverage-based use case.
It does not claim to reproduce the combined EEG/MEG or individual-MRI pipeline
exactly. Older amplitude-derived L2-MNE and eLORETA maps can still be imported,
but they are legacy/exploratory workflows and are not generated by the normal
rebuild action.
</p>

<h3>Surface Source Maps</h3>
<p>
During processing, FPVS Toolbox averages each participant's repetitions while
the EEG waveform is still signed. It then computes an MNE source spectrum from
that averaged time series, converts source power to amplitude, aligns and sums
the project-selected oddball harmonics, and computes a source-space z-score
against neighboring frequency bins. This ordering avoids projecting a scalp
magnitude map that has already discarded phase and polarity.
</p>
<p>
Exact FPVS Toolbox frequency bins are intentional: a target must fall on the
processed recording's FFT grid, and the software does not silently substitute a
nearby bin. Noise uses offsets -10 through -2 and +2 through +10, removes one
minimum and one maximum, and uses population standard deviation. These Toolbox
rules are reported explicitly because they are adaptations, not a claim that
every detail matches the reference scripts.
</p>
<p>
Participant z-score maps are summarized only after the participant-level source
calculation. You can view the arithmetic mean, a 20% trimmed mean, or the median.
</p>

<h3>Cluster-Based Permutation Mask</h3>
<p>
Cluster based permutation tests are widely used in statistical analysis, and these were employed in 
Hauk et al., 2021 across the group level to ensure that the group level heatmaps only display 
vertices that were significant across the entire group. Cluster based permutation tests are very conservative and 
can therefore significantly reduce the amount of painted vertices that appear on the surface or in the 
eLORETA 3D view. 

In short, FPVS Toolbox checks each source point across participants. Source
points that pass the cluster-forming threshold and touch each other are grouped
into clusters. Then the toolbox repeats the analysis with random sign flips to
ask a question: how large could the biggest cluster be if there were no
consistent group response?
</p>
<p>
Only clusters that are larger than expected under that permutation test remain
visible in the masked display. You can disable this mask if you'd like, but just be aware that 
the source map you see without the mask could be influenced by an outlier or small number of participants
across your dataset, so use caution when interpreting data without the mask. 
</p>

<h3>eLORETA Volume View</h3>
<p>
Previously generated eLORETA volume manifests remain importable for comparison.
The current normal rebuild does not run eLORETA or relabel those amplitude-derived
maps as time-domain source PSD. A future version can add an independently
validated time-domain eLORETA workflow if it is needed.
</p>

<h3>fsaverage Anatomy</h3>
<p>
FPVS Toolbox intentionally uses MNE's fsaverage template anatomy and the canonical
BioSemi64 EEG montage instead of participant MRI and coregistration data. This
makes one consistent source workflow available to EEG projects without an MRI
pipeline, but anatomical locations remain approximate. Use the maps for
descriptive inference and figures, and report the template-model limitation.
The inverse also uses MNE's ad-hoc diagonal EEG noise covariance because the
Toolbox workflow does not require a separate resting/noise recording; this is a
reported adaptation of the Hauk study rather than an exact reproduction.
</p>

<h3>References And Background</h3>
<ul>
  <li><a href="https://doi.org/10.1016/j.neuroimage.2021.118460">Hauk et al. (2021)</a>: combined EEG/MEG FPVS source estimation for face-selective responses.</li>
  <li><a href="https://github.com/olafhauk/FPVS_sweep">Hauk FPVS_sweep repository</a>: public analysis scripts that informed the time-domain source-PSD sequence.</li>
  <li><a href="https://doi.org/10.1016/j.neuroimage.2022.119177">Hauk, Stenroos, and Treder (2022)</a>: practical guidance on what EEG/MEG source estimates can and cannot localize.</li>
  <li><a href="https://doi.org/10.1162/imag_a_00414">Hauk et al. (2025)</a>: word-selective FPVS EEG/MEG source-space analyses.</li>
  <li><a href="https://mne.tools/stable/generated/mne.datasets.fetch_fsaverage.html">MNE fsaverage dataset</a>: the template anatomy files used by the visualizer.</li>
  <li><a href="https://mne.tools/stable/auto_tutorials/forward/35_eeg_no_mri.html">MNE template MRI source modeling note</a>: why template source reconstruction should not be over-interpreted.</li>
</ul>
"""

LORETA_METHOD_INFO = ToolInfoContent(
    key="loreta_method",
    title="About LORETA Source Maps",
    html=LORETA_METHOD_INFO_HTML,
    size=SurfaceSize(width=660, height=640, min_width=520, min_height=460),
)

__all__ = ["LORETA_METHOD_INFO", "LORETA_METHOD_INFO_HTML"]
