pyinstaller `
  --clean `
  --noconfirm `
  --windowed `
  -n FPVS_Toolbox `
  --paths=src `
  -i "assets/ToolBox_Icon.ico" `
  --collect-all mne `
  --collect-data mne `
  --hidden-import=mne.io.bdf `
  --hidden-import=scipy `
  --hidden-import=scipy._cyutility `
  --hidden-import=pandas `
  --hidden-import=numpy `
  --hidden-import=statsmodels `
  --hidden-import=pyvista `
  --hidden-import=statsmodels `
  --hidden-import=patsy `
  -D src/main.py